//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_ErrorLog
    {
        public int Id { get; set; }
        public string DBName { get; set; }
        public string SPName { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public Nullable<int> ErrorSeverity { get; set; }
        public Nullable<int> ErrorState { get; set; }
        public Nullable<int> ErrorLine { get; set; }
    }
}
